include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    unnecessary_library_name: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "example/**"

linter:
  rules:
    # Essential rules for code quality
    avoid_dynamic_calls: true
    cancel_subscriptions: true
    close_sinks: true
    literal_only_boolean_expressions: true
    throw_in_finally: true
    always_declare_return_types: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    sized_box_shrink_expand: true
    sort_child_properties_last: true
    use_super_parameters: true
